---
- name: install maven
  apt: pkg=maven state=present
  when: exhibitor_build_connection != 'local'

- file:
    path: "{{exhibitor_build_dir}}"
    state: directory
  connection: "{{exhibitor_build_connection}}"
- file:
    path: "{{exhibitor_build_dir}}/exhibitor-{{exhibitor_version}}"
    state: directory
  connection: "{{exhibitor_build_connection}}"
- file: path={{exhibitor_install_dir}} state=directory

- name: create exhibitor pom.xml
  connection: "{{exhibitor_build_connection}}"
  template: >
    src=pom.xml.j2
    dest={{exhibitor_build_dir}}/exhibitor-{{exhibitor_version}}/pom.xml

- name: build exhibitor
  connection: "{{exhibitor_build_connection}}"
  command: >
    mvn clean package
    chdir={{exhibitor_build_dir}}/exhibitor-{{exhibitor_version}}
    creates={{exhibitor_build_dir}}/exhibitor-{{exhibitor_version}}/target

- name: install exhibitor
  when: exhibitor_build_connection != 'local'
  command: >
    mv target/exhibitor-1.0.jar {{exhibitor_install_dir}}/exhibitor.jar
    chdir=/opt/src/exhibitor-{{exhibitor_version}}
    creates={{exhibitor_install_dir}}/exhibitor.jar


- name: install exhibitor
  when: exhibitor.build_connection == 'local'
  copy:
    src: "{{exhibitor_build_dir}}/exhibitor-{{exhibitor_version}}"
    dest: "{{exhibitor_install_dir}}/exhibitor.jar"


- name: create start script
  template: >
    src=start.sh.j2
    dest={{exhibitor_install_dir}}/start.sh
    mode=0755

- name: change ownership on exhibitor directory
  file: >
    path={{exhibitor_install_dir}}
    state=directory
    recurse=yes
    owner=zookeeper
    group=zookeeper

- name: configure exhibitor
  template: >
    src={{item}}.j2
    dest={{exhibitor_install_dir}}/{{item}}
    mode=0644
    owner=zookeeper
    group=zookeeper
  with_items:
    - defaults.conf
    - log4j.properties
    - realm
    - web.xml
  notify:
    - restart exhibitor
  sudo: yes
  sudo_user: zookeeper

- name: configure exhibitor s3 credentials
  template: >
    src={{item}}.j2
    dest={{exhibitor_install_dir}}/credentials.properties
    mode=0644
    owner=zookeeper
    group=zookeeper
  notify:
    - restart exhibitor
  sudo: yes
  sudo_user: zookeeper
  when: >
    exhibitor_config_type == 's3' and
    exhibitor_s3_access_key_id is defined and
    exhibitor_s3_access_secret_key is defined

- name: create exhibitor none config directory
  file: >
    path={{exhibitor_none_config_dir}}
    state=directory
    recurse=yes
    owner=zookeeper
    group=zookeeper
  notify:
    - restart exhibitor
  when: exhibitor_config_type == 'none'

- name: add init script
  template: >
    src=exhibitor.init.j2
    dest=/etc/init.d/exhibitor
    mode=0755
