---
- include: zookeeper.yml
  when: zookeeper_install_type == "source"
  tags:
  - zookeeper

- include: zookeeper-package.yml
  when: zookeeper_install_type == "package"
  tags:
  - zookeeper

- include: exhibitor.yml
  tags:
  - exhibitor
